### ISSUE TITLE
Inquiry as to why you have ported our SVN repository to GitHub

### ISSUE THREAD

**Issue by ariel-phet** [mleoking/PhET#1]
Hello @mleoking ,

I am the Director of Development of the PhET project, and we noticed you made a copy of our SVN repository in your account. Could you tell us your planned usage of this repo? Was it merely for personal learning? We are generally curious when people make copies of our code, even though it is of course open source.

Thanks!

Ariel

**Comment by mleoking** [comment]
Hi Ariel, @ariel-phet 

Thank you so much for developing the PhET project. I made a copy of its repository in my github collection for personal learning. 

Leo

**Comment by ariel-phet** [comment]
@mleoking thank you for your response. Closing.
